device: cuda
seed: 42
train_file: ["./dataset/RSTPReid/processed_data/train.json"]
train_image_root: "./dataset/RSTPReid/imgs"
batch_size_train: 4


temp: 0.07
alpha: 0.4
weak_pos_pair_probability: 0.1
mlm_probability: 0.15
mrtd_mask_probability: 0.3
queue_size: 65536


bert_config: "configs/config_bert.json"
text_encoder: bert-base-uncased
embed_dim: 256
max_words: 50


image_res: 384
vision_width: 768


momentum: 0.995
solver:
    optimizer: AdamW
    lr: 1e-5
    lr_factor: 5.0
    bias_lr_factor: 2.0
    weight_decay: 4e-5
    weight_decay_bias: 0.0
    alpha: 0.9
    beta: 0.999


scheduler:
    total_epochs: 30
    milestones: [20, 50]
    gamma: 0.1
    warmup_factor: 0.1
    warmup_epochs: 1
    warmup_method: linear
    lr_scheduler: cosine
    target_lr: 0
    power: 0.9
